@startuml

Journey : String name
Journey "1" --> "*" Page : pages
Journey "1" --> "1..*" Step : steps
Journey "0.." --> "*" Journey: background

Page : String name
Page : URL url
Page "1" -->  "*" Step: checks
Page "1" --> "*" Selector : {name}

interface Step

Step : void execute(ExecutionContext)
Step : String getDescription()

Check --|> Step
Check *-- Selector

ClickOn  --|> Step
ClickOn *-- Selector

DismissAlert --|> Step

ExecuteScript --|> Step
ExecuteScript : String script

GoTo --|> Step
GoTo : String place

Select --|> Step
Select *-- Selector
Select : String value

Submit --|> Step

SwitchToDefaultContent --|> Step

SwitchToFrameByIndex--|> Step
SwitchToFrameByIndex : int index

StepSwitchToFrameByName --|> Step
StepSwitchToFrameByName : String frameName

Type --|> Step
Type : String text

Uncheck --|> Step
Uncheck *-- Selector

AttributeShouldBe --|> Step
AttributeShouldBe : String attributeName
AttributeShouldBe : String expectedValue
AttributeShouldBe *-- Selector

Capture --|> Step

TitleShouldBe --|> Step
TitleShouldBe : String expectedTitle

PageShouldBe --|> Step
PageShouldBe --> Page

ShouldBeChecked --|> Step
ShouldBeChecked *-- Selector

ShouldNotBeChecked --|> Step
ShouldNotBeChecked *-- Selector

TextOfShouldBe --|> Step
TextOfShouldBe *-- Selector
TextOfShouldBe : String expectedText

TitleShouldBe --|> Step
TitleShouldBe : String expectedTitle

TitleShouldContain --|> Step
TitleShouldContain : String value

Selector : String value
Selector : boolean isTargetName()


@enduml