@startuml

Journey : String name
Journey "1" --> "*" Page
Journey "1" --> "1..*" Step

Page : String name
Page : URL url
Page "1" -->  "*" Step: checks

interface Step

Step : void execute(ExecutionContext)
Step : String getDescription()

Step <|-- GoTo
Step <|-- ClickOn
Step <|-- AttributeShouldBe
Step <|-- Check
Step <|-- ExecuteScript

Selector : String value
GoTo : String place

ClickOn *-- Selector
AttributeShouldBe : String attributeName
AttributeShouldBe : String expectedValue
AttributeShouldBe *-- Selector
Check *-- Selector

ExecuteScript : String script

ExecutionContext : WebDriver getDriver()
ExecutionContext .. Step
ExecutionContext "*" --> "*" Page

@enduml